# Generated by Django 2.2.3 on 2019-07-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_featuredpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='author_gender',
            field=models.CharField(choices=[('male', 'Male')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='author_img',
            field=models.ImageField(upload_to='media/author_images'),
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/post_images'),
        ),
    ]
