# Generated by Django 2.2.3 on 2019-07-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190730_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='author_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
    ]
