# Generated by Django 2.2.3 on 2019-08-01 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190730_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ctg_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/ctg_images'),
            preserve_default=False,
        ),
    ]
