# Generated by Django 2.2.3 on 2019-08-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
