# Generated by Django 2.2.3 on 2019-08-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ctg_image',
            field=models.ImageField(upload_to='ctg-images/'),
        ),
    ]
