# Generated by Django 2.2.4 on 2019-11-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190822_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
