# Generated by Django 2.2.13 on 2020-07-18 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=45)),
                ('author_img', models.ImageField(upload_to='media/author_images')),
                ('author_description', models.TextField()),
                ('author_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('author_facebook', models.URLField(blank=True, null=True)),
                ('author_twitter', models.URLField(blank=True, null=True)),
                ('author_linkedin', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
